site_name: Airulefy Docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - ホーム: index.md
  - インストール方法: installation.md
  - クイックスタート: quickstart.md
  - CLIリファレンス: cli_reference.md
  - 設定方法: configuration.md
  - 動作原理: how_it_works.md
  - DevContainer: devcontainer.md
  - 貢献: contributing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
