name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry --version
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Run E2E tests
      run: |
        # テスト用ディレクトリを作成
        mkdir -p test_workspace
        cd test_workspace
        
        # E2Eテスト用の実行環境を作成
        mkdir -p .ai
        echo "# Test Rule" > .ai/rule.md
        echo "default_mode: copy\ntools:\n  cursor: {}\n  cline: {}\n  copilot: {}\n  devin: {}" > .ai-rules.yml
        
        # テストを実行
        poetry run airulefy generate
        
        # 生成されたファイルを表示
        find . -type f | grep -v "__pycache__" || true
        
        # E2Eテストを実行
        cd ..
        poetry run pytest tests/test_e2e.py -v
    
    - name: Archive generated files
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-artifacts-standalone
        path: test_workspace
        if-no-files-found: warn
